apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secrets.yaml

namespace: fast-food-base

commonLabels:
  app: fast-food
  component: application
