apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data: 
  POSTGRES_USER: ZmlhcA== 
  POSTGRES_PASSWORD: ZmlhcA== 
  SPRING_DATASOURCE_USERNAME: ZmlhcA==  
  SPRING_DATASOURCE_PASSWORD: ZmlhcA==
