apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: fast-food-dev

patches:
- path: patches/deployment-patch.yaml

configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - DATABASE_URL=jdbc:postgresql://db-service:5432/fiap-dev
